#############################################################################
# Makefile for building: VIAAC
# Generated by qmake (2.01a) (Qt 4.8.1) on: Sun Jan 5 18:21:14 2014
# Project:  VIAAC.pro
# Template: app
# Command: /usr/bin/qmake-qt4 -spec /usr/share/qt4/mkspecs/linux-g++ -o Makefile VIAAC.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_WEBKIT -DQESP_NO_UDEV -D__linux__ -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -std=c++0x -g -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -Icallendar -Imusic -I/usr/include/qextserialport/src -I.
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib/i386-linux-gnu -lfmod -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake-qt4
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = /usr/include/qextserialport/src/qextserialport.cpp \
		/usr/include/qextserialport/src/qextserialenumerator.cpp \
		/usr/include/qextserialport/src/qextserialport_unix.cpp \
		/usr/include/qextserialport/src/qextserialenumerator_linux.cpp \
		main.cpp \
		callendar/Activity.cpp \
		callendar/Day.cpp \
		callendar/Hour.cpp \
		callendar/libFunc.cpp \
		callendar/TimeDB.cpp \
		callendar/TimeHandler.cpp \
		music/MusicMaker.cpp \
		music/PortSender.cpp \
		music/Song.cpp \
		music/statFile.cpp \
		music/libTreater.cpp \
		callendar/CronTab.cpp \
		callendar/Event.cpp \
		callendar/DataBase.cpp moc_MusicMaker.cpp \
		moc_PortSender.cpp
OBJECTS       = qextserialport.o \
		qextserialenumerator.o \
		qextserialport_unix.o \
		qextserialenumerator_linux.o \
		main.o \
		Activity.o \
		Day.o \
		Hour.o \
		libFunc.o \
		TimeDB.o \
		TimeHandler.o \
		MusicMaker.o \
		PortSender.o \
		Song.o \
		statFile.o \
		libTreater.o \
		CronTab.o \
		Event.o \
		DataBase.o \
		moc_MusicMaker.o \
		moc_PortSender.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/include/qextserialport/src/qextserialport.pri \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		VIAAC.pro
QMAKE_TARGET  = VIAAC
DESTDIR       = 
TARGET        = VIAAC

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: VIAAC.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/include/qextserialport/src/qextserialport.pri \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/i386-linux-gnu/libQtGui.prl \
		/usr/lib/i386-linux-gnu/libQtCore.prl
	$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -o Makefile VIAAC.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/include/qextserialport/src/qextserialport.pri:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/i386-linux-gnu/libQtGui.prl:
/usr/lib/i386-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -o Makefile VIAAC.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/VIAAC1.0.0 || $(MKDIR) .tmp/VIAAC1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/VIAAC1.0.0/ && $(COPY_FILE) --parents /usr/include/qextserialport/src/qextserialport.h /usr/include/qextserialport/src/qextserialenumerator.h /usr/include/qextserialport/src/qextserialport_global.h /usr/include/qextserialport/src/qextserialport_p.h /usr/include/qextserialport/src/qextserialenumerator_p.h callendar/Activity.hpp callendar/Day.hpp callendar/Hour.hpp callendar/libFunc.hpp callendar/TimeDB.hpp callendar/TimeHandler.hpp music/libTreater.hpp music/MusicMaker.hpp music/PortSender.hpp music/Song.hpp callendar/CronTab.hpp callendar/Event.hpp callendar/DataBase.hpp callendar/C_MACRO.hpp music/statFile.hpp .tmp/VIAAC1.0.0/ && $(COPY_FILE) --parents /usr/include/qextserialport/src/qextserialport.cpp /usr/include/qextserialport/src/qextserialenumerator.cpp /usr/include/qextserialport/src/qextserialport_unix.cpp /usr/include/qextserialport/src/qextserialenumerator_linux.cpp main.cpp callendar/Activity.cpp callendar/Day.cpp callendar/Hour.cpp callendar/libFunc.cpp callendar/TimeDB.cpp callendar/TimeHandler.cpp music/MusicMaker.cpp music/PortSender.cpp music/Song.cpp music/statFile.cpp music/libTreater.cpp callendar/CronTab.cpp callendar/Event.cpp callendar/DataBase.cpp .tmp/VIAAC1.0.0/ && (cd `dirname .tmp/VIAAC1.0.0` && $(TAR) VIAAC1.0.0.tar VIAAC1.0.0 && $(COMPRESS) VIAAC1.0.0.tar) && $(MOVE) `dirname .tmp/VIAAC1.0.0`/VIAAC1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/VIAAC1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_qextserialport.cpp moc_qextserialenumerator.cpp moc_MusicMaker.cpp moc_PortSender.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_qextserialport.cpp moc_qextserialenumerator.cpp moc_MusicMaker.cpp moc_PortSender.cpp
moc_qextserialport.cpp: /usr/include/qextserialport/src/qextserialport_global.h \
		/usr/include/qextserialport/src/qextserialport.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) /usr/include/qextserialport/src/qextserialport.h -o moc_qextserialport.cpp

moc_qextserialenumerator.cpp: /usr/include/qextserialport/src/qextserialport_global.h \
		/usr/include/qextserialport/src/qextserialenumerator.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) /usr/include/qextserialport/src/qextserialenumerator.h -o moc_qextserialenumerator.cpp

moc_MusicMaker.cpp: music/PortSender.hpp \
		music/statFile.hpp \
		/usr/include/qextserialport/src/qextserialport.h \
		/usr/include/qextserialport/src/qextserialport_global.h \
		music/Song.hpp \
		music/MusicMaker.hpp
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) music/MusicMaker.hpp -o moc_MusicMaker.cpp

moc_PortSender.cpp: music/statFile.hpp \
		/usr/include/qextserialport/src/qextserialport.h \
		/usr/include/qextserialport/src/qextserialport_global.h \
		music/PortSender.hpp
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) music/PortSender.hpp -o moc_PortSender.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

qextserialport.o: /usr/include/qextserialport/src/qextserialport.cpp /usr/include/qextserialport/src/qextserialport.h \
		/usr/include/qextserialport/src/qextserialport_global.h \
		/usr/include/qextserialport/src/qextserialport_p.h \
		moc_qextserialport.cpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qextserialport.o /usr/include/qextserialport/src/qextserialport.cpp

qextserialenumerator.o: /usr/include/qextserialport/src/qextserialenumerator.cpp /usr/include/qextserialport/src/qextserialenumerator.h \
		/usr/include/qextserialport/src/qextserialport_global.h \
		/usr/include/qextserialport/src/qextserialenumerator_p.h \
		moc_qextserialenumerator.cpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qextserialenumerator.o /usr/include/qextserialport/src/qextserialenumerator.cpp

qextserialport_unix.o: /usr/include/qextserialport/src/qextserialport_unix.cpp /usr/include/qextserialport/src/qextserialport.h \
		/usr/include/qextserialport/src/qextserialport_global.h \
		/usr/include/qextserialport/src/qextserialport_p.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qextserialport_unix.o /usr/include/qextserialport/src/qextserialport_unix.cpp

qextserialenumerator_linux.o: /usr/include/qextserialport/src/qextserialenumerator_linux.cpp /usr/include/qextserialport/src/qextserialenumerator.h \
		/usr/include/qextserialport/src/qextserialport_global.h \
		/usr/include/qextserialport/src/qextserialenumerator_p.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qextserialenumerator_linux.o /usr/include/qextserialport/src/qextserialenumerator_linux.cpp

main.o: main.cpp callendar/TimeHandler.hpp \
		callendar/C_MACRO.hpp \
		callendar/Day.hpp \
		callendar/libFunc.hpp \
		callendar/TimeDB.hpp \
		callendar/DataBase.hpp \
		callendar/Event.hpp \
		callendar/Hour.hpp \
		callendar/Activity.hpp \
		callendar/CronTab.hpp \
		music/MusicMaker.hpp \
		music/PortSender.hpp \
		music/statFile.hpp \
		/usr/include/qextserialport/src/qextserialport.h \
		/usr/include/qextserialport/src/qextserialport_global.h \
		music/Song.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

Activity.o: callendar/Activity.cpp callendar/Activity.hpp \
		callendar/C_MACRO.hpp \
		callendar/Event.hpp \
		callendar/Hour.hpp \
		callendar/libFunc.hpp \
		callendar/Day.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Activity.o callendar/Activity.cpp

Day.o: callendar/Day.cpp callendar/Day.hpp \
		callendar/C_MACRO.hpp \
		callendar/libFunc.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Day.o callendar/Day.cpp

Hour.o: callendar/Hour.cpp callendar/Hour.hpp \
		callendar/C_MACRO.hpp \
		callendar/libFunc.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Hour.o callendar/Hour.cpp

libFunc.o: callendar/libFunc.cpp callendar/libFunc.hpp \
		callendar/C_MACRO.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o libFunc.o callendar/libFunc.cpp

TimeDB.o: callendar/TimeDB.cpp callendar/TimeDB.hpp \
		callendar/C_MACRO.hpp \
		callendar/DataBase.hpp \
		callendar/Event.hpp \
		callendar/Hour.hpp \
		callendar/libFunc.hpp \
		callendar/Day.hpp \
		callendar/Activity.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o TimeDB.o callendar/TimeDB.cpp

TimeHandler.o: callendar/TimeHandler.cpp callendar/TimeHandler.hpp \
		callendar/C_MACRO.hpp \
		callendar/Day.hpp \
		callendar/libFunc.hpp \
		callendar/TimeDB.hpp \
		callendar/DataBase.hpp \
		callendar/Event.hpp \
		callendar/Hour.hpp \
		callendar/Activity.hpp \
		callendar/CronTab.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o TimeHandler.o callendar/TimeHandler.cpp

MusicMaker.o: music/MusicMaker.cpp music/MusicMaker.hpp \
		music/PortSender.hpp \
		music/statFile.hpp \
		/usr/include/qextserialport/src/qextserialport.h \
		/usr/include/qextserialport/src/qextserialport_global.h \
		music/Song.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MusicMaker.o music/MusicMaker.cpp

PortSender.o: music/PortSender.cpp music/PortSender.hpp \
		music/statFile.hpp \
		/usr/include/qextserialport/src/qextserialport.h \
		/usr/include/qextserialport/src/qextserialport_global.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o PortSender.o music/PortSender.cpp

Song.o: music/Song.cpp music/Song.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Song.o music/Song.cpp

statFile.o: music/statFile.cpp music/statFile.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o statFile.o music/statFile.cpp

libTreater.o: music/libTreater.cpp music/libTreater.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o libTreater.o music/libTreater.cpp

CronTab.o: callendar/CronTab.cpp callendar/CronTab.hpp \
		callendar/C_MACRO.hpp \
		callendar/DataBase.hpp \
		callendar/Event.hpp \
		callendar/Hour.hpp \
		callendar/libFunc.hpp \
		callendar/Day.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o CronTab.o callendar/CronTab.cpp

Event.o: callendar/Event.cpp callendar/Event.hpp \
		callendar/C_MACRO.hpp \
		callendar/Hour.hpp \
		callendar/libFunc.hpp \
		callendar/Day.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Event.o callendar/Event.cpp

DataBase.o: callendar/DataBase.cpp callendar/DataBase.hpp \
		callendar/C_MACRO.hpp \
		callendar/Event.hpp \
		callendar/Hour.hpp \
		callendar/libFunc.hpp \
		callendar/Day.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o DataBase.o callendar/DataBase.cpp

moc_MusicMaker.o: moc_MusicMaker.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_MusicMaker.o moc_MusicMaker.cpp

moc_PortSender.o: moc_PortSender.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_PortSender.o moc_PortSender.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

